#include <conio.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <time.h>
#include <env.h>
#include <sys/name.h>
#include <sys/mman.h>
#include <sys/dev.h>
#include <sys/kernel.h>
#include <sys/sendmx.h>
#include <sys/proxy.h>
#include <process.h>
#include <sys/sched.h>
#include <sys/qnx_glob.h>
#include <sys/vc.h>
#include <signal.h>
#include <fcntl.h>
#include <math.h>
#include <sys/types.h>
#include <malloc.h>
#include <semaphore.h>
